name: BE CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}

      - name: Build Docker image
        working-directory: ./apps/backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app:latest .
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:latest
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to Servers
        env:
          SERVERS: ${{ secrets.EC2_SERVERS }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          set -e
          for server in $(echo "$SERVERS" | jq -r '.[]'); do
            echo "Deploying to $server"
            ssh -o StrictHostKeyChecking=no ubuntu@"$server" bash -s <<EOF
              set -e
              sudo docker pull ${DOCKER_USERNAME}/backend-app:latest
              sudo docker stop backend-container || true
              sudo docker rm backend-container || true

              sudo docker run -d \
                --name backend-container \
                --env-file /home/ubuntu/.env \
                -p 5001:5001 \
                -p 5002:5002 \
                ${DOCKER_USERNAME}/backend-app:latest
          EOF
            done
